// Coach Types
export type CoachType = 
  | 'strategy' 
  | 'brand' 
  | 'marketing' 
  | 'leadership' 
  | 'customer_experience';

// Coaching Styles (personality/approach variations)
export type CoachingStyle = 'mentor' | 'realist' | 'strategist';

// Coaching Stages
export type CoachingStage = 'discovery' | 'plan_generation' | 'support';

export interface QuickReply {
  label: string;
  value: string;
}

export interface CoachMessage {
  role: 'coach' | 'user';
  content: string;
  quickReplies?: QuickReply[];
  timestamp: Date;
}

export interface ProjectContext {
  projectType: string;
  businessName?: string;
  targetAudience: string;
  uniqueValue: string;
  primaryGoal: string;
  tone: string;
  additionalNotes?: string;
}

export interface ProjectSection {
  id: string;
  name: string;
  purpose: string;
  keyElements: string[];
  copyGuidance?: string;
  priority: 'must-have' | 'recommended' | 'optional';
}

export interface StyleRecommendations {
  tone: string;
  colorSuggestions: string[];
  layoutStyle: string;
}

export interface ProjectOutline {
  summary: string;
  sections: ProjectSection[];
  styleRecommendations: StyleRecommendations;
}

/**
 * Business Plan - Strategic plan generated by coaches
 * Replaces/extends ProjectOutline for business strategy coaching
 */
export interface BusinessObjective {
  id: string;
  description: string;
  measurable: string; // How success is measured
}

export interface BusinessPhase {
  name: string;
  timeframe: string; // e.g., "0-30 days", "30-90 days", "90+ days"
  actions: BusinessAction[];
}

export interface BusinessAction {
  id: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
}

export interface BusinessMetric {
  metric: string;
  target: string;
  checkpoint: string; // When to review
}

export interface BusinessRisk {
  risk: string;
  mitigation: string;
}

export interface BusinessPlan {
  objectives: BusinessObjective[];
  strategyOverview: string;
  phases: BusinessPhase[];
  metrics: BusinessMetric[];
  risks: BusinessRisk[];
}

export interface CoachingSession {
  id: string;
  userId: string;
  messages: CoachMessage[];
  status: 'in_progress' | 'outline_ready' | 'approved';
  
  // Legacy fields (for backward compatibility with web project coaching)
  outline: ProjectOutline | null;
  extractedContext: ProjectContext | null;
  
  // New multi-coach fields
  coachType?: CoachType;
  coachingStyle?: CoachingStyle;
  stage?: CoachingStage;
  businessProfile?: import('./business').BusinessProfile;
  plan?: BusinessPlan | null; // Business strategic plan
  
  createdAt: Date;
  updatedAt: Date;
}


